# Colors - https://github.com/olimorris/onedarkpro.nvim
[colors.primary]
background  = "#000000"
foreground  = "#abb2bf"

[colors.normal]
black       = "#000000"
red         = "#ef596f"
green       = "#89ca78"
yellow      = "#e5c07b"
blue        = "#61afef"
magenta     = "#d55fde"
cyan        = "#2bbac5"
white       = "#abb2bf"

[colors.bright]
black       = "#1a1a1a"
red         = "#f38897"
green       = "#a9d89d"
yellow      = "#edd4a6"
blue        = "#8fc6f4"
magenta     = "#e089e7"
cyan        = "#4bced8"
white       = "#c8cdd5"

[colors.cursor]
text        = "CellBackground"
cursor      = "CellForeground" # syntax-cursor-color

[colors.selection]
text        = "CellForeground"
background  = "#434852"
