# Colors - https://github.com/olimorris/onedarkpro.nvim
[colors.primary]
background  = "#282c34"
foreground  = "#abb2bf"

[colors.normal]
black       = "#282c34"
red         = "#e06c75"
green       = "#98c379"
yellow      = "#e5c07b"
blue        = "#61afef"
magenta     = "#c678dd"
cyan        = "#56b6c2"
white       = "#abb2bf"

[colors.bright]
black       = "#3e4451"
red         = "#e9969d"
green       = "#b3d39c"
yellow      = "#edd4a6"
blue        = "#8fc6f4"
magenta     = "#d7a1e7"
cyan        = "#7bc6d0"
white       = "#c8cdd5"

[colors.cursor]
text        = "CellBackground"
cursor      = "CellForeground" # syntax-cursor-color

[colors.selection]
text        = "CellForeground"
background  = "#5c6370"
